apiVersion: apps/v1
kind: Deployment
metadata:
  name: newt-newt-main-tunnel
spec:
  template:
    spec:
      initContainers:
        - name: blueprint-merger
          image: docker.io/mikefarah/yq:4
          command: ["/bin/sh", "-c"]
          args:
            - |
              yq eval-all '. as $item ireduce ({}; . * $item)' /config/*.yaml > /data/blueprint.yaml
          volumeMounts:
            - name: blueprints-raw
              mountPath: /config
              readOnly: true
            - name: blueprints-merged
              mountPath: /data
      containers:
        - name: newt
          args:
            - --blueprint-file=/etc/pangolin/blueprint.yaml
          volumeMounts:
            - name: blueprints-merged
              mountPath: /etc/pangolin
              readOnly: true
      volumes:
        - name: blueprints-raw
          configMap:
            name: blueprints-raw
        - name: blueprints-merged
          emptyDir: {}
