global:
  domain: argocd.cornfakes.xyz

configs:
  params:
    server.insecure: true

server:
  service:
    type: LoadBalancer

  ingress:
    enabled: true
    controller: generic
    labels: {}
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect@kubernetescrd
    ingressClassName: traefik
    hostname: "argocd.cornfakes.xyz"
    path: /
    pathType: Prefix
    tls: false

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

repoServer:
  podLabels:
    app.kubernetes.io/instance: argocd
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true