apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-controller
  namespace: sealed-secrets
spec:
  template:
    spec:
      containers:
      - name: sealed-secrets-controller
        args:
        - --update-status
        - --key-renew-period=720h30m
