apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - disable-local-path.yaml

patches:
- target:
    kind: DaemonSet
    name: longhorn-csi-plugin
    namespace: longhorn-system
  patch: |-
    - op: replace
      path: /spec/template/spec/nodeSelector
      value: {}
    - op: replace
      path: /spec/template/spec/tolerations
      value:
      - key: storage
        operator: Equal
        value: longhorn
        effect: NoSchedule
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node.kubernetes.io/disk-pressure
        operator: Exists
        effect: NoSchedule
      - key: node.kubernetes.io/memory-pressure
        operator: Exists
        effect: NoSchedule
      - key: node.kubernetes.io/network-unavailable
        operator: Exists
        effect: NoSchedule
      - key: node.kubernetes.io/not-ready
        operator: Exists
        effect: NoSchedule
      - key: node.kubernetes.io/pid-pressure
        operator: Exists
        effect: NoSchedule
      - key: node.kubernetes.io/unreachable
        operator: Exists
        effect: NoSchedule
      - key: node.kubernetes.io/unschedulable
        operator: Exists
        effect: NoSchedule
