fullnameOverride: sealed-secrets-controller

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Mantenir les claus en cas de reinstal·lació
commandArgs:
  - --update-status
  - --key-renew-period=0

# Assegurar que el controller està disponible
podSecurityContext:
  fsGroup: 65534
