apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kured
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kured
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: kured
    spec:
      serviceAccountName: kured
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: node
          value: storage
          effect: NoSchedule
      hostPID: true
      restartPolicy: Always
      volumes:
        - name: sentinel
          hostPath:
            path: /var/run
            type: Directory
      containers:
        - name: kured
          image: ghcr.io/kubereboot/kured:1.20.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080
              name: metrics
          env:
            - name: KURED_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /sentinel
              name: sentinel
              readOnly: true
          command:
            - /usr/bin/kured
            - --reboot-sentinel=/sentinel/reboot-required
            - --reboot-command=/usr/bin/systemctl reboot
            - --pre-reboot-node-labels=kured=rebooting
            - --post-reboot-node-labels=kured=done
            - --period=5m
