apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

resources:
- ../../base
- longhorn-ingress.yaml
- longhorn-settings.yaml

patches:
- patch: |-
    - op: replace
      path: /data/storageclass.yaml
      value: |
        kind: StorageClass
        apiVersion: storage.k8s.io/v1
        metadata:
          name: longhorn
          annotations:
            storageclass.kubernetes.io/is-default-class: "true"
        provisioner: driver.longhorn.io
        allowVolumeExpansion: true
        reclaimPolicy: "Delete"
        volumeBindingMode: Immediate
        parameters:
          numberOfReplicas: "2"
          staleReplicaTimeout: "30"
          fromBackup: ""
          fsType: "ext4"
          dataLocality: "disabled"
          unmapMarkSnapChainRemoved: "ignored"
          disableRevisionCounter: "true"
          dataEngine: "v1"
          backupTargetName: "default"
  target:
    kind: ConfigMap
    name: longhorn-storageclass
- patch: |-
    - op: replace
      path: /spec/type
      value: LoadBalancer
    - op: remove
      path: /spec/ports/0/nodePort
  target:
    kind: Service
    name: longhorn-frontend

patchesStrategicMerge:
- longhorn-node-selector.yaml
- longhorn-user-components-patch.yaml
