apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

resources:
- ../../base
- longhorn-ingress.yaml
- longhorn-settings.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/type
      value: LoadBalancer
    - op: remove
      path: /spec/ports/0/nodePort
  target:
    kind: Service
    name: longhorn-frontend

patchesStrategicMerge:
- longhorn-node-selector.yaml
- longhorn-user-components-patch.yaml
