longhornManager:
  nodeSelector: {}
  tolerations:
  - key: "storage"
    operator: "Equal"
    value: "longhorn"
    effect: "NoSchedule"

longhornDriver:
  nodeSelector: {}
  tolerations: []

longhornUI:
  nodeSelector:
    node-role.kubernetes.io/storage: "true"
  tolerations:
  - key: "storage"
    operator: "Equal"
    value: "longhorn"
    effect: "NoSchedule"

csi:
  kubeletRootDir: /var/lib/kubelet
  attacherReplicaCount: 3
  provisionerReplicaCount: 3
  resizerReplicaCount: 3
  snapshotterReplicaCount: 3

service:
  ui:
    type: LoadBalancer

preUpgradeChecker:
  jobEnabled: false

defaultSettings:
  defaultDataPath: /var/lib/longhorn
  taintToleration: "storage=longhorn:NoSchedule"
  systemManagedComponentsNodeSelector:
    node-role.kubernetes.io/storage: "true"
  createDefaultDiskLabeledNodesOnly: true

ingress:
  enabled: true
  ingressClassName: traefik
  host: longhorn.cornfakes.xyz
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect@kubernetescrd