preUpgradeChecker:
  jobEnabled: false

global:
  nodeSelector:
    node-role.kubernetes.io/storage: "true"

defaultSettings:
  systemManagedComponentsNodeSelector: "node-role.kubernetes.io/storage:true"
  defaultDataPath: /var/lib/longhorn
  defaultReplicaCount: "2"

longhornManager:
  nodeSelector:
    node-role.kubernetes.io/storage: "true"
  tolerations:
    - key: "storage"
      operator: "Equal"
      value: "longhorn"
      effect: "NoSchedule"

longhornDriver:
  nodeSelector:
    node-role.kubernetes.io/storage: "true"
  tolerations:
    - key: "storage"
      operator: "Equal"
      value: "longhorn"
      effect: "NoSchedule"

longhornUI:
  nodeSelector:
    node-role.kubernetes.io/storage: "true"
  tolerations:
    - key: "storage"
      operator: "Equal"
      value: "longhorn"
      effect: "NoSchedule"

frontend:
  service:
    type: LoadBalancer