service:
  ui:
    type: LoadBalancer

preUpgradeChecker:
  jobEnabled: false

ingress:
  enabled: true
  ingressClassName: traefik
  host: longhorn.cornfakes.xyz
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect@kubernetescrd