---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCA07cr4HMP3McRSE6WfmXjBMrhvYfJDHlV/INWbi5up5XUoO6+VOR9+CS7JL91dp/EVotNmjBsHIfuWUy9pFvYJzejsnsXgbDg2U/HKK+QMvys70LfW7UEz9+4yEvNyEnjf1ci2sZkrYXUTJYnIpfgB5+ZQSWppCu52PLe5j37CV8UZvRezPBG1TJzvFOE0w4mCqyPxTL7U2j+wsf/GN3hyNpp3fWu6av8ZpvvhE4bo1MGrHmiQUulKnsHWQteuBoclPAhbbuhoqQDGz9UCc2xBlUYEXPWYfS1sNnmDBNVwHdD1qtZX7dPVmUIdwiaw4HJwWzeXoneWjRHb6iS5MJgWQhV3fRxXQRR7IpblrR1bfYRlGeFkAfKo4qRHvtzNm7EbJ7afGp/e6nR58/1JcLv3q+WPgAN8oyRf6PQaSTwvGFeDA/++ppG0dJKfo9Uhwo+NfmlUMwpSF5Y1PTZBO6H2Ss4BuuCOZRtFDpUPRLl94rcpQpDe59ALHYxXohVAwaO6d7iPc9OpqZBxFErxKQOwqkZkrnzF3cxUPmxCLj/JT7Lhjk8YULdYDTRTxjXg7StG24A7vPJ2A7iy+2dg2xmvxyDELm7O5nmOUCwA3L+7I6sdp45TfmaD4JhePBhvxRZv+nZhMvP9M+fPBNFjhr/zea0pGqcdAd1wb7kvP6oIJleRXK088pGqbmf8sv4qyyth8oMehTfEyIEqBXsVXh9/ryAxgaDT5ZViOVIFssUXCP+B+s4LTImTipe7Q==
    admin-user: AgCBWpzEkfQoMwIeh/g8PzIKbuklmYgZfh5IvTdEHcIjlWhL2GXhhUHYDu38I4Cnq97wa/LyL+pqrE4tExorZEci/60oVyBTznHF8uwV6WfjfrEu1u1uxrzEYxCGiYyilp0UKPW/PpTnbHB7IPWba1zsIeDFIxxZo9lBtIVhDG4IjanF3FD9YO5lIm7Xaejb24F/Ocj7ohd/dtGD5lNNsJVbhKajdGTbL/twbvg/d1TcIJWZWq3jBxJFKC/cDU/fDsLK5JlavLpV9N8FuW5gUVbb4Lj3zu8fmRbya1ANKiMrmq71FS/btW8SQHT0oWmFVtXTdeKO6BApXdKui1Mc88hpQj/gyZiu4EcDgvveq2e7UtXvs3M8pu/56whLpxLDFnnxutPPliHp5gLH1rb+JE1FU4sN7xgvd4N/DOX+bVgp3QlISTJBeI+I19Syxvo2VZenFA//01YuexkbyCpLr/sxsY9eRtOJ4zic8Gwo5JxsAzjpDi8ssSApqUaNBNWJN2/+p4bVEpKRQWk9bTEbG03JYAC8/AX8k30U1p8CLht1nP9Rpkc9yR4P1rk7F6qZPx6fBhpMKhey8cRsAWUuUSTmkDAH2vSzKc+wohE1/5J6DwN1Z/M76iDYYoWnxZDENq6Dp/vqBRNCUZaCVHlR4dNjW2nJJ9xPSN0eSnu/azMm5kJ3gT8yq+/yjPsut6FTXG9U/NTqFQ==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
