---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAVrPl0J54MksU5TPkXwfuMnpEF062514/gcyxjJXIM8P1/apC583qm0Wgpooi8rBh+rYXyqPVUQMo1un4geNHJscUo1DhoM4egLE1vi4h3UEScNbYI9FIvNkgsQxedpRolnDHw3bEI53vXswXMPu/e/wsjEI6J6+ORibmA12muldq+qwIjcA+gtAtiuZBkfgwsBoKhyNbxRE4JPTs9e5A0jWi3oGKkR4ukacQ2xhFLkerYJ7bK4ctagabihslXPLcSaWhWJ9vZBclyMMxnc4Xr7cRyXQNdjU4Lnl/+nbRjkMgiXc++4368R9nLej5mFuzX+mzkWd5Z1jWdG+OB8R5y0kELY2JyIYXAWlUVJ6nLe/QBxAEkCH1qLarpmtB2cfFny1IHdiRF4YqIryGtao8D5qTy0oHnDvvdx8R+jUPjpdZUHRoIoMYcFDV9ku4g94lQKdXh6qJQ6fdN1Zh2vaxR/z7p7MbMByVenxN43/8wzZcfZhXAKjbHVUwldhOQo1pIfKJ+fqCgl8pba9j77qr53UCv2DLC9licy1bEn1xQOgl0L4XzmQ9G+l94lK5NnbgqFVTelEuDmQPhWrnH4za3f/9KqMWUFZr/dTL81kP6XiUJwSsWR144zJjYWe0M8gHhhw/9wK10J/aGc93bdzOtPHdWejxOqMAqj3RKtx5O55aVfZG3LQ5SLfne/OtNLjXkFHfv9p3osVnImAupObjXglZY0+QySXJaU7MAdnJm2Vl1bU6HxVIyzUdGJA==
    admin-user: AgAFnCm4IwCQ1k47x2AdFG2mBxdRl8jPxFPYNu8zGbH7Om4jZDONP7AtnqhjkH+Nt6DlUDvM/AbWiwphF2ah/DfqlFKhHCCgnooyc0Pk+ib6WezsSPbUBS2ktQ34xPWO0JtWYfBfYxMddu1VOe0+8SjbzQZhmT4gemns/XZg0W3M7wTzW4wOJQftReeQzfL4YloHBK7x9K5MVcQIrK9If4oV+yuLOE/TTwWidYelhIVBabMF07Epf9RWkTLiy32MEXBGQiGoi2C8+Tdg0zr2KhwIyjyayigrv/k6ROl5bvsitS4zFNFhQ/pvWi0JAnqbEmA7OAW1eTdQ8x83z3rbzDud4ZMAes9V90qVAXww62CdkE976Ga5wFsPLod9cSs+NOPMY9wdTzmE6bfIJq1qouc0lqoEDe5NtYENUEpsxVHOP/en0KRdsYvYTC82ruYPc8QFPrzxRrir8E2vPOIOzVDZNJcl/46suQv4PUGwTm1gHc4hiJrljp6G4rjTY4EbgG0wgr3nKq3Sn6oM7NUeEYW4cuRxCPg8opW6dCOCY1bPAWO+4P/qBRPlul/+JijgsGiwJ/i2/SHw+voXyVB2D+kJGbhgkIyuZ6Trxn454NqU19FAY3wwn/ucPkNoN8zuSpBggCM3rgEItbSiIcxiqKHlSk95tg2cJ9Zt0Jd/TtquIlcBTYfF63i0aKI5tL+/+Ot+D9IAwA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
