apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-60"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  project: default
  sources:
  - repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: "37.1.2"
    helm:
      valueFiles:
      - $values/apps/traefik/helm/values.yaml
  - repoURL: https://github.com/eudaldgr/homelab-gitops.git
    targetRevision: main
    ref: values
  - repoURL: https://github.com/eudaldgr/homelab-gitops.git
    path: apps/traefik/k8s-manifests
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true