apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-omada
  namespace: omada
spec:
  dnsNames:
    - omada.cornfakes.xyz
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-issuer
  secretName: cert-omada
  usages:
    - digital signature
    - key encipherment
