deployment:
  enabled: true
  kind: DaemonSet

nodeSelector:
  node-role.kubernetes.io/control-plane: "true"

globalArguments:
- "--global.checknewversion"
- "--global.sendanonymoususage=false"
- "--serversTransport.insecureSkipVerify=true"

tlsStore:
  default:
    defaultCertificate:
      secretName: wildcard-cornfakes-xyz-tls

service:
  type: LoadBalancer
  externalTrafficPolicy: Local

ports:
  web:
    port: 80
    hostPort: 80
    containerPort: 80
  websecure:
    port: 443
    hostPort: 443
    containerPort: 443

providers:
  kubernetesCRD:
    allowCrossNamespace: true
    allowExternalNameServices: true
    allowEmptyServices: true
    nativeLBByDefault: false
  kubernetesIngress:
    allowExternalNameServices: true
    allowEmptyServices: true
    publishedService:
      enabled: true
      pathOverride: ""
    nativeLBByDefault: false

resources:
  requests:
    cpu: 50m
    memory: 200Mi
  limits:
    memory: 200Mi

rbac:
  enabled: true
