apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: metallb-system
spec:
  template:
    spec:
      containers:
      - name: controller
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            memory: 100Mi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: speaker
  namespace: metallb-system
spec:
  template:
    spec:
      containers:
      - name: speaker
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            memory: 100Mi
