apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: speaker
  namespace: metallb-system
spec:
  template:
    spec:
      tolerations:
      - key: "node"
        operator: "Equal"
        value: "storage"
        effect: "NoSchedule"
