apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-plugin
  namespace: inteldeviceplugins-system
spec:
  template:
    spec:
      securityContext:
        seLinuxOptions:
          type: spc_t
      containers:
        - name: intel-gpu-plugin
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
      volumes:
        - name: kubeletsockets
          hostPath:
            path: /var/lib/kubelet/device-plugins
