controller:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      memory: 100Mi

speaker:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      memory: 100Mi

  frr:
    enabled: false

  reloader:
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        memory: 100Mi

  frrMetrics:
    enabled: false