---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: traefik
spec:
  encryptedData:
    api-token: AgANgCOcuS+9mMR6y5u+OKOw/f/Bhy3mEx+wbaCsX0TA10LKdY6BHVmHsYj7zRpoyDQgl1I3p9Osk8LkTWMCmEIPeTawHxdMEp+c1FTd4MGjavrXdYqnqzyjYAMnAEecCJ2x9qG/ISn3/OL9dFgcEReYEvbZyeqMn5p4TLAF2RUmEnMPUntlc5Et67DNOyNpHlmCZxerdJzdND72tl3ftDHsqKZEkmaA+rEK/V5Oyc9CbG2FVGUtGF8tu+9s4Uvtv7/FZMiDOAIMqHsZaeLkY8+bIP8h6Ie3BUeTzM4h4g1lYf+AZYNvJEKHCTHxZv+ZS088R6Z+ZjKFLGIP1IJF3Y67/IK0FzSzpKvKBsdieh6DlV9B0Z9gONOmqmRucEwU7r5aJkh+9Gsk9+80zRtanIhdy07HRM/JVWNqduTKxERkwA52gu5ODxf4HTplUQV9+WIL0ZCOHuTTLq4mpmBu1vipd76/zIiZJTlMrzRdPjBI/xaJrTcben0lJR8M9UZoKJgO9mOiAqz53YZyjCedB7X77zSNE2tuRMD0+p7hCU7SQsNjwI4oEQpgO6EVn3bFNQbi5MSRFPN9Llepm+nIO6VIExXWXPflx8kQWz2dqk/9OhpiTI4CBEXcZuvdT0WtlsuBoirVy9/QiXHmxBw0f22H2Zt506JT/Dc9CJXN+ek7JAGviHA0LsIXUwyMmN/q2FxAgJHPq9se5UgcSDulqsD4JWyYmiFYQq5YFInT2YYeee49RJGGUsmq
  template:
    metadata:
      name: cloudflare
      namespace: traefik
