---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: traefik
spec:
  encryptedData:
    api-token: AgBVa+JTFws7eGK3ANowNqpjQhbLcbDHMj+7jOnGZvvUEVfXuLwPXOy0PQ0nK+rThc01DUUOU020/pZsaxd3lkY2GdAFzky0b2TDJwa99A1J1C6rqCPo7SolewQUGZ85bWMhkYx6E0MYOG3UhmPWJ6KWB36B3bXgQZbleai2he2iQE1AfacIpXBOWLukNjV1al+cs5th2lwqHsNcoXUCgGJp9Ldv0vozHRSNJv2Cy40yrJg0EtbDaQ84gSewlSI4MouzdT0/b0/9e8mAqiN+tCW4ECEbSqTTHzM9pjl4iZIAhIK5/cAa742VWdK0dUqYWbfa3Yjc5G6THLOMVip12a9g44hVuLj4dY3vpKudvp2pe7YTNY4zTl8zfOh8QFMUz+wBX94VwGbyWUYWdAvsutVQMQqGEdIkqmT80FyYb/gdUK2YXcRvOFyteAQrU8wMm804e0qGALyDrPChvQwQiMqrBPZbQW2GPuXiJjSJJA/0p+P4VBzHpTBEUhtUCSLZoYXlDbsOmC1YLZWvARP2W9oEH6GCb6KHATmdoHEIs1vZ/dIwfT5bjVCrgY9eZqeaEQqiZWtSylsBZMAR+mYhvfNNGtnpTIhMuurDQkitMmcakdVgR/rEgNTnS1O3v3lXngNii4Pj85EeSHJFs3FRiRPXUb8pmox0IBVkZzVlzD8Y8WaVz+abzNIq8er8OIvv98RQObgWnueiQbNioDKQjzqKrsrDunfPaFu9kwry9Fv++gAQBqRYy2GU
  template:
    metadata:
      name: cloudflare
      namespace: traefik
