---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: traefik
spec:
  encryptedData:
    api-token: AgAu1VjRPpSpdXY6Vf5G7+KA7sofWW0Vi8Bdjuf2GC7EQzv+u6qvB17taOkO85UgZTZIsrQ8JAkfzXg7SDVo9jK23WaIDzurzcQCkVbyVhV5S7S24dQ40O7+cSpjII6Yl6nxpMMuxFjTK/8TW74+it7JgM7pivDP7t1O63ahGm0YMcw9bdjscjO12McpTGqETccE4URg08VifvbOC5ELXGEsg2ObMc78cz0DG5K0d6DHi5h5gRwNqZkaZQauuEVbpyCEBM6UWINn/28mfGbkKw8sW5xVi813aZ7fIXmJS8ftDlX9yELXP6x7ZMuHlzue2DwHlL3sYSfwAjY67LaQm+4WJqlEVXAlxwKcHYQF0KE/iPh/8mjikNkbIcHGn3QRw1ebnfMX09EnPxvXgyeVodurmiDuZE7dMJOCd7OkSak9RJwpqp0yRhT5qLay7wm5V8Umo/mRi9Jdat8iyxi4EWg1iMapA0zDNJhuJr6/UiIRnA3Un7ZGXS6EgEzylYmFNDECizQajLxfQqfTBR5GJE7ggwk0cuEb2U2zuuvzNXEaCzQxE/cxP0bBEn7/3Nwy7qdwVnwvK8pfxSmopgjUF0klbB+XIRGMmWduoQzxcwmiw1sH2lXPxwQp4EX14uqR0juSjemCPYk8SYYpP7gNL4bK3LBnrKAIyWNXAYwI8ocM8W6gK6u+gydta0ka+NGB2/BOj93k5BxTwakuTZLALgAcis166EeJn9uKBthyzXa/IWpg2CE4z6ua
  template:
    metadata:
      name: cloudflare
      namespace: traefik
