---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare
  namespace: traefik
spec:
  encryptedData:
    api-token: AgDDyb5pp9sjzd1NYLAO2rB5Cl5tPyLWS7y/oZfMvNdW6VHQaAIRe87ymmW/0enOOJp8Z4odO6VLDJ2NEyepP/FovAzMgn9AXB8Efp1OepXNLqYRRjeyWVwHxFOPpVH/H9+Yzn/5T0gEx+/DyfpUtA+qisl8dFn7CP9BpZImbLGE9P4FZ/mXJdBIL7QBIIXHpZVBBuGfDsWxlf5QCtHdyMjK0BHkymkxR76f/s9MZuQ5KhMTtfbq4cTwWXl/XKj/6CbSScolIHZ877fNqVCBNOguBElH98GFMeWz4Usqbf9zel6nTBkvCtKrvIJOkQeZswX+/OI4kZtYerFEUwZ8yRLthpUFxh+pFXpd4SBUaZ7PuFx5Jai9G9ZQGLbYnXT66WtOq+ii5+6s2uWYNxzQPBDWEJI78q6vHfpaFEi4C3oenV50JdlYps3BJbruF4GPBy4YkSZzGj4mrHFhM+iRGw54WzSH+RW2bnqKiZ+JbUDMq9QkBgnd623vN1FORTHbK7Xwq3rhShwSD6Zpl86kEtZTJBZTCAP5Gk45bJPbImYUA3C45wQr3SGHw6h4WfcxsdEiL6kvlR/ggPo3EETItxCK8va+Z3bagCZPOiWXQ+fufzbQMNwMk9QueONf640wMtdIiMT6wM80EOlOMYdnSJtIjAbBIQ5dYhcG+9Cem/R1ba5kWKYYRFZ5ptU/FfzSTaeGXfjauckJpqgNGiplW+RIkgF21vc63GfV4kZ3M6OLY9Qk7QkgQRyz
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare
      namespace: traefik
